# Yazi 基本設定

[mgr]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"
ratio = [1, 4, 3]

[opener]
edit = [
    { run = 'micro "$@"', block = true }
]

[preview]
wrap = "yes"
tab_size = 2
max_width = 600
max_height = 900
